// ---------------------------------------------------------------
// FIELD OPTIONS LIBRARY
// Pre-written options for free-text fields in the RAMS Builder.
// Picking an option inserts the text into the field — it stays a
// normal editable textarea afterwards, so any option can be
// tweaked into a custom entry. No AI involved, just reusable text.
// ---------------------------------------------------------------

const FIELD_OPTIONS = {

  manualHandling: [
    { label: "Minimal — light materials only", text: "Minimal manual handling on this project. All materials under 5kg, single-person lift, no mechanical aids required." },
    { label: "Moderate — boards/panels, two-person lift", text: "Manual handling of boards/panels kept to a minimum using team lifts (two-person). Materials positioned as close to the work area as possible prior to lifting. Operatives have undergone basic manual handling training." },
    { label: "Heavier items — mechanical aids required", text: "Manual handling assessment carried out for heavier items. Mechanical aids (trolleys, board lifters, pallet trucks) used wherever possible. Loads broken into manageable sizes. Team lifts for any item that cannot be moved safely by one person." },
    { label: "Not applicable", text: "Not applicable — no manual handling beyond normal hand tools for this task." }
  ],

  handArmVibration: [
    { label: "Minimal — short duration hand tools only", text: "Short-duration works — hand tools and battery drill only. HAVS report not required; trigger time well within HSE exposure action value." },
    { label: "Moderate — powered tools, trigger time monitored", text: "Powered hand tools used intermittently. Trigger time to be monitored and kept within HSE exposure action value (2.5 m/s²). Tool usage rotated between operatives on longer tasks." },
    { label: "Not applicable", text: "Not applicable — no vibrating tools used for this task." }
  ],

  noise: [
    { label: "Minimal — hand tools only", text: "Hand tools only. Noise generation minimal and short duration; no ear defenders required." },
    { label: "Moderate — power tools, no assessment needed", text: "Power tools used intermittently. Noise kept to the shortest practicable duration given the occupied building. Ear defenders available if required." },
    { label: "Noisy works — assessment/hearing protection required", text: "Noise assessment carried out for this task. Ear defenders to be worn during noisy activities. Legal noise action levels (80/85/87 dB(A)) not to be exceeded. Others nearby protected from noise generated by this work." }
  ],

  radiation: [
    { label: "Not applicable (most common)", text: "Not applicable — no laser setting-out required for this task." },
    { label: "Laser level used for setting out", text: "Class 2 laser level used for setting out only. Warning signage displayed while in use; operatives briefed not to stare into the beam." }
  ],

  accessEgress: [
    { label: "Single operative, standard site access", text: "Access via main site entrance as directed by the Site Manager. Sign in on arrival and complete site induction before starting work. Exclusion zone/signage maintained around the work area throughout." },
    { label: "Goods lift / loading bay access", text: "Access via the loading bay — sign in on arrival. All materials and labour to access the work floor via the Goods Lift. Site induction to be completed before starting work." },
    { label: "Occupied building — extra care needed", text: "Building is occupied and in use during works. Access via designated route as directed by the Site Manager. Exclusion zone/signage maintained around the work area at all times; work area not left unattended in a partially-completed state." }
  ],

  workAtHeightPersons: [
    { label: "No work at height", text: "Not applicable — all work carried out at standing/bench height; no access equipment required." },
    { label: "Step/plant access (client-provided)", text: "Access via step/plant equipment provided and inspected by the Site Manager before use. Three points of contact maintained at all times. Work at height kept to short duration, no longer than 5 minutes per activity." },
    { label: "Podium / tower / MEWP", text: "Access via podium steps / mobile tower / MEWP as appropriate for the task, erected/operated only by trained, competent operatives. Equipment inspected before use and tagged. Guardrails in place at all times." },
    { label: "Stepladder — last resort, permit required", text: "Stepladder use only where no other means of access is reasonably practicable, and only where not prohibited by the main contractor. Daily inspection and permit required. Three points of contact maintained; top step/platform never used." }
  ],

  workAtHeightFalling: [
    { label: "Not applicable", text: "Not applicable — no work above head height in this scope." },
    { label: "Standard falling object controls", text: "Tools and materials controlled while working at height; nothing set down loose above head height. Exclusion zone/signage maintained beneath the work area given other occupants are present in the building." },
    { label: "Tool tethering required", text: "Tools tethered while working at height to prevent falling and striking anyone below. Exclusion zone established and signed beneath the work area for the duration of the task." }
  ],

  wasteRemoval: [
    { label: "Small quantity — removed by operative", text: "Waste generated (offcuts, packaging) bagged and removed from site by the operative, disposed of via Interior Impressions Ltd's normal waste route. No on-site skip required." },
    { label: "Larger quantity — skip/segregated waste", text: "Waste segregated on site in line with the Principal Contractor's waste management procedures. Skip/waste area location confirmed with the Site Manager. Materials delivered on a just-in-time basis to minimise accumulation." }
  ],

  housekeeping: [
    { label: "Tidy-as-you-go, single task", text: "Materials kept together at the immediate work area — no separate storage required for this short-duration task. Tidy-as-you-go maintained throughout; offcuts and packaging removed from site on completion." },
    { label: "Designated storage area, larger job", text: "Designated, barriered storage area agreed with the Site Manager. Sheet materials laid flat or secured upright as appropriate. Walkways kept clear and unobstructed. All rubbish and debris cleared from the work site daily." }
  ],

  leaksSpills: [
    { label: "Not applicable (most common)", text: "Not applicable — no liquids or chemical substances used on this task." },
    { label: "Adhesives/sealants in use", text: "Small quantities of adhesive/sealant used, kept in original labelled containers. Spill kit available. Any spillage contained and cleaned up immediately, waste disposed of per COSHH guidance." }
  ],

  securityArrangements: [
    { label: "As Principal Contractor requirements", text: "As Principal Contractor/main contractor site security requirements — sign in/out, ID badge worn at all times, work area secured at the end of each visit." },
    { label: "Not applicable / standard site rules apply", text: "No additional security arrangements beyond standard site sign-in/sign-out procedures." }
  ],

  pedestrianTraffic: [
    { label: "Not applicable (most common)", text: "Not applicable — no vehicle or pedestrian traffic rerouting required for this task." },
    { label: "Rerouting required", text: "Pedestrian/vehicle routes rerouted around the work area as directed by the Site Manager. Signage and barriers in place before work commences; routes reinstated on completion." }
  ],

  fireSafety: [
    { label: "Not applicable / no hot works", text: "Not applicable. No hot works required for this task." },
    { label: "Standard fire precautions", text: "Standard site fire precautions apply — fire exits and escape routes kept clear at all times, no combustible materials stored near heat sources." },
    { label: "Hot works involved", text: "Hot Works permit required — 2-hour fire watch, appropriate fire extinguishers on site (minimum 13A rating, at least one water/foam), extinguishers tested within the last 12 months." }
  ],

  taskLighting: [
    { label: "Interior Impressions responsible (standard)", text: "Interior Impressions will be responsible for task lighting for their operatives." },
    { label: "Provided by main contractor", text: "General access/safety lighting provided by the Principal Contractor. Interior Impressions responsible for any additional task-specific lighting required for safe working." }
  ],

  communication: [
    { label: "Single operative — briefed directly", text: "This RAMS briefed directly to the operative prior to attendance. As a single-operative task, no wider toolbox talk is required — understanding confirmed with the Site Manager as part of induction." },
    { label: "Small team — toolbox talk", text: "This RAMS briefed to the team via toolbox talk before work commences. Supervisor to confirm all operatives understand the content and have the opportunity to raise questions or concerns." },
    { label: "Non-English speaking operatives", text: "Where an operative's first language is not English, this RAMS and site induction will be translated and an English-speaking team member assigned as translator to ensure full understanding." }
  ],

  environmental: [
    { label: "Minimal impact (standard)", text: "Waste removed from site via Interior Impressions Ltd's normal waste route. Noise and dust kept to a minimum given the occupied building. No spill, F-gas, or wastewater discharge risks associated with this task." },
    { label: "Dust/noise sensitive location", text: "Dust and noise generation minimised given the sensitivity of the location — dust extraction/suppression used where cutting is required, noisy works kept to the shortest practicable duration and coordinated with the Site Manager." }
  ],

  hsMonitoring: [
    { label: "Single operative, self-monitored", text: "Standards monitored via pre-use checks by the operative, who also acts as task supervisor, and sign-off with the Site Manager on completion." },
    { label: "Supervised team", text: "Standards monitored via daily supervisor checks, toolbox talk records, and sign-off with the Site Manager on completion. Any concerns raised immediately to the Site Manager." }
  ],

  emergencyArrangements: [
    { label: "Standard — work stops, first aid, 999 if needed", text: "In the event of an injury, work stops immediately, first aid is administered, and emergency services are called if required. Fire/evacuation arrangements and assembly point to be confirmed as part of the Site Manager's induction on arrival." },
    { label: "Work at height specific", text: "In the event of a fall or injury while working at height, work stops immediately, first aid is administered, and emergency services are called if required. All operatives briefed on the location of the nearest first aid point and fire assembly area during induction." }
  ],

  rescuePlan: [
    { label: "No specialist plan needed (low-height, short duration)", text: "No specialist rescue plan required given short-duration, low-height access. Standard first aid response is sufficient." },
    { label: "MEWP/tower — rescue plan required", text: "Rescue plan in place for the access equipment in use: descent/lowering procedure known to all operatives, rescue equipment available on site, and emergency services contact confirmed in the event self-rescue is not possible." }
  ],

  loneWorking: [
    { label: "Not applicable — team of 2+ on site", text: "Not applicable — more than one operative on site throughout this task." },
    { label: "Single operative — standard check-in", text: "This is a lone-working task. Operative to check in with the office at the start and end of the task, and if any delay beyond 30 minutes occurs. Mobile phone signal confirmed adequate on site before starting. Office contact: 01628 665821." },
    { label: "Single operative — higher-risk task, more frequent check-ins", text: "This is a lone-working task involving a higher-risk activity (e.g. work at height). Operative to check in with the office at the start, at agreed intervals during the task, and at completion. Mobile phone signal confirmed adequate on site. If contact is missed, the office will attempt to reach the operative immediately and escalate to site management/emergency services if unreachable within 15 minutes." }
  ],

  occupationalHealth: [
    { label: "Standard — hierarchy of controls followed", text: "Control measures follow the hierarchy of prevention: elimination and substitution considered first, followed by engineering controls, then administrative controls, with PPE as the last resort. No specific occupational health surveillance identified for this task based on the risk assessment." },
    { label: "Health surveillance required (dust/noise/vibration exposure)", text: "Hierarchy of controls applied — elimination/substitution, engineering controls, administrative controls, PPE as last resort. Operatives regularly exposed to dust, noise, or vibration on this type of work are included in the company's periodic health surveillance programme." }
  ],

  dustRespiratory: [
    { label: "Minimal — hand tools, no cutting", text: "No significant dust-generating activity on this task. Standard good housekeeping (clean as you go) is sufficient; no RPE required beyond general site PPE." },
    { label: "Some cutting — extraction/RPE required", text: "Dust-generating activity limited to cutting plasterboard/timber. On-tool extraction or wet cutting used where practicable. FFP3 RPE worn when cutting; face-fit tested. No dry sweeping — M-class vacuum used for clean-up." },
    { label: "Significant dust — strip-out/demolition", text: "Dust hazards eliminated/reduced where practicable by selecting the lowest-dust method. On-tool extraction used on all cutting tools. Dedicated cutting area segregated from other personnel with barriers/signage. Water suppression used when cutting stone/concrete. No dry sweeping — M/H-class vacuum used. FFP3 RPE worn, face-fit tested to the individual." }
  ],

  quality: [
    { label: "Standard — self-inspection, sign-off on completion", text: "Work checked by the operative against the specification/drawings on completion. Any defects rectified before sign-off with the Site Manager. Photographs taken of completed work for the project record." },
    { label: "Formal snagging / ISO 9001 checkpoint", text: "Work subject to the company's quality control procedures (ISO 9001) — completed work inspected and signed off before handover. Any snagging items raised are tracked to close-out. Photographic record retained for quality assurance." }
  ]
};
